# config.yml
local_backend: true

backend:
  name: git-gateway
  repo: cnoss/thesis
  branch: main # Branch to update (optional; defaults to master)

media_folder: 'assets/uploads'

collections:
  - name: 'research-questions'
    label: 'Proposals'
    folder: '_research-questions'
    create: true
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'work' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Datum', name: 'datum', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Status"
        name: "status"
        widget: "select"
        options: ["proposal", "in-progress", "finished"]
      - label: "Keywords"
        name: "keywords"
        widget: "list"
        allow_add: true
        default: ["Design"]
  - name: 'works'
    label: 'Arbeiten'
    folder: '_works'
    create: true
    slug: "{{related-folder}}-{{slug}}-{{date}}"
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'work-result' }
      - { label: 'Autor*in', name: 'author', widget: 'string' }
      - { label: 'Zugeh√∂riger Ordner', name: 'related-folder', widget: 'string', required: true }
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - label: 'Datum'
        name: date
        widget: "datetime"
        default: ""
        date_format: "DD.MM.YYYY" # e.g. 24.12.2021
        format: "LLL"
        picker_utc: true
        required: true
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Typ"
        name: "type"
        widget: "select"
        options: ["Praxisprojekt", "Bachelorarbeit", "Masterarbeit"]
      - label: "Keywords"
        name: "keywords"
        widget: "list"
        allow_add: true
        default: ["Design"]        
      - { label: 'Kooperationspartner', name: 'partner', widget: 'string' }
      - { label: 'Kooperationspartner Website', name: 'partner-url', widget: 'string' }
